services:
  - type: web
    name: razorpay-charge-api
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0
    envVars:
      - key: PORT
        value: 8054
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    autoDeploy: true
    region: oregon  # or frankfurt, singapore, etc.
